name: CI

on:
    push:
        branches:
            - uat

jobs:
    ci:
        name: Upload UAT
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true

            - uses: Roblox/setup-foreman@v1
              with:
                  version: "^1.0.0"
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Report tool versions
              run: rojo --version

            - run: npm ci

            - run: npm run compile

            - name: Deploy
              run: rojo upload --api_key $API_KEY --universe_id 3901447895 --asset_id 10793767154
              env:
                  API_KEY: ${{ secrets.API_KEY }}
